config/routes.rb
Rails.application.routes.draw do

  root "classrooms#index"

  resources :users, only: [ :new, :create ]
  resources :teachers, controller: 'users', type: 'Teacher', only: [ :new, :create ]
  resources :students, controller: 'users', type: 'Student', only: [ :new, :create ]
  resources :parents, controller: 'users', type: 'Parent', only: [ :new, :create ]
  resources :sessions, only: [ :new, :create, :destroy ]

  resources :classrooms do

    resources :student_memberships, only: [ :create, :new, :destroy]
    resources :parent_memberships, only: [ :create, :new, :destroy]

    resources :messages do
      resources :comments, except: [ :create ]
      resources :comments, only: [ :create ], as: "create_comment"
    end

    resources :homeworks, controller: 'messages', type: 'Homework', only: [ :new, :create ]
    resources :generals, controller: 'messages', type: 'General', only: [ :new, :create ]
    resources :reminders, controller: 'messages', type: 'Reminder', only: [ :new, :create ]
  end

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :teacher, class_name: "User"
  has_many :messages, dependent: :destroy
  has_and_belongs_to_many :students, :join_table => :student_memberships
  has_and_belongs_to_many :parents, :join_table => :parent_memberships
  has_many :student_memberships, dependent: :destroy
  has_many :parent_memberships, dependent: :destroy

  validates :classroom_name, presence: true 
  validates :teacher, presence: true

  def check_teacher(classroom, user)
    classroom.teacher == user
  end

  def check_student_membership(classroom, user)
    StudentMembership.where("classroom_id = ? AND student_id = ?", classroom.id, user.id)
  end

  def check_parent_membership(classroom, user)
    ParentMembership.where("classroom_id = ? AND parent_id = ?", classroom.id, user.id)
  end

  def as_json(options={})
    super(methods:[:teacher])
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController

  before_filter :restrict_access
  before_filter :teacher_access, only: [:new, :create, :destroy]

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)
    num = (100_000 + Random.rand(1_000_000 - 100_000))
    @classroom.passcode = num
    @classroom.teacher = @current_user

    if @classroom.save
      redirect_to classroom_path(@classroom)
    else
      render :new
    end
  end

  def show
    @classroom = Classroom.find(params[:id])
  end

  def index
    @classrooms = Classroom.all
  end

  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy
    redirect_to classrooms_path
  end

  protected

  def classroom_params
    params.require(:classroom).permit( :classroom_name, :passcode)
  end

  def check_valid_membership(classroom)
  end

end

app/helpers/classroom_helper.rb
module ClassroomHelper
end

app/views/classrooms/index.html.erb
<div class="custom-list">
  <h1>Welcome to the ClassroomDashboard, <%= @current_user.name %>!</h1>
  <% if @current_user.is_a?(Teacher) %>
    Add a <%= link_to "new classroom!", new_classroom_path  %>.
  <% end %>
</div> 

<div class="container-fluid">
  <%= react_component(
    'ClassList', 
    classrooms: @classrooms, 
    current_user: @current_user, 
    userType: @current_user.type,
    memberships: @current_user.memberships_of_user(@current_user) 
  ) %>
</div>

app/views/classrooms/new.html.erb
<div class="custom-standard-view">  
  <h1>New Classroom</h1>
  <p><%= link_to "Go back to classroom list", classrooms_path %></p>

  <%= form_for @classroom do |f| %>
    <div>
      <%= f.label :classroom_name %><br>
      <%= f.text_field :classroom_name %>
    </div>
    <div>
      <%= f.submit "Submit" %> 
    </div>
  <% end %>
</div>

app/views/classrooms/show.html.erb
<div class="container-fluid">
  <div class="custom-classroom-view"> 
    <h1>Welcome to <%= @classroom.classroom_name %>,  <%= @current_user.name %>!</h1>
    <p>Teacher: <%= @classroom.teacher.name %></p>
    <p><%= link_to "Go back to classroom list", classrooms_path %></p>
    <% if @current_user.is_a?(Teacher) %>
      <p><%= link_to "Create a message!", new_classroom_message_path(@classroom, @message) %></p>
    <% end %>
    <hr>
    <p>If you have forgotten, the class passcode is <%= @classroom.passcode %></p>

    <% if @classroom.messages.length > 0 %>
      <% @classroom.messages.each do |message| %>
        <div>
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title" ><%= message.title %></h3>
                <h5><%= message.type %></h5>
              </div>
            <div class="panel-body panel-overflow">
              <p><%= message.text %></p>
              <% if message.comments.length > 0 %>
                <% message.comments.each do |comment| %>
                <% username = (User.find(comment.user_id).username) %>

                <div class="container ">
                  <div class="well well-sm">
                    <%= react_component("CommentBox", comment: comment, username: username ) %>
                  </div>
                </div>
                <% end %>
              <% end %>

              <p><%= link_to "Reply to the message", new_classroom_message_comment_path(@classroom.id, message.id, @comment) %></p>
            </div>    
          </div>
        </div>
        
      <% end %>
    <% end %>
  </div>
</div>