config/routes.rb
Rails.application.routes.draw do

  root "classrooms#index"

  resources :users, only: [ :new, :create ]
  resources :teachers, controller: 'users', type: 'Teacher', only: [ :new, :create ]
  resources :students, controller: 'users', type: 'Student', only: [ :new, :create ]
  resources :parents, controller: 'users', type: 'Parent', only: [ :new, :create ]
  resources :sessions, only: [ :new, :create, :destroy ]

  resources :classrooms do

    resources :student_memberships, only: [ :create, :new, :destroy]
    resources :parent_memberships, only: [ :create, :new, :destroy]

    resources :messages do
      resources :comments, except: [ :create ]
      resources :comments, only: [ :create ], as: "create_comment"
    end

    resources :homeworks, controller: 'messages', type: 'Homework', only: [ :new, :create ]
    resources :generals, controller: 'messages', type: 'General', only: [ :new, :create ]
    resources :reminders, controller: 'messages', type: 'Reminder', only: [ :new, :create ]
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :comments, dependent: :destroy

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
  validates :type, presence: true

  def memberships_of_user(user)
    if user.is_a?(Student)
      return StudentMembership.where("student_id = ?", user.id)
    elsif user.is_a?(Parent)
      return ParentMembership.where("parent_id = ?", user.id)
    end
  end

  class << self
    def types
      %w(Teacher Student Parent)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [ :destroy ]
  before_action :set_type

  def new
    @user = type_class.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to classrooms_path
    else
      render :new
    end
  end

  protected

  def set_type 
    @type = type
  end

  def type
    User.types.include?(params[:type]) ? params[:type] : 'User'
  end

  def type_class
    type.constantize
  end

  def set_user
    @user = type_class.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :name, :email, :type, :password, :password_confirmation) 
  end
end



















# class TeachersController < UsersController

#   def create
#     @teacher = Teacher.new(teacher_params)

#     if @teacher.save
#       session[:teacher_id] = @teacher.id
#     end
#   end

#   protected

#   def teacher_params
#     params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
#   end
# end

# class StudentsController < UsersController

#   def create
#     @student = Student.new(student_params)

#     if @student.save
#       session[:student_id] = @student.id
#     end
#   end

#   protected

#   def student_params
#     params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
#   end
# end

# class ParentsController < UsersController

#   def create
#     @parent = Parent.new(parent_params)

#     if @parent.save
#       session[:parent_id] = @parent.id
#     end
#   end

#   protected

#   def parent_params
#     params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
#   end
# end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/new.html.erb
  <div class="custom-standard-view">
  <% if @current_user %>
    <% redirect_to classrooms_path %>
  <% else %>
    <h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <div>
        <%= f.label :username %><br>
        <%= f.text_field :username %>
      </div>
      <div>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.radio_button(:type, "Teacher") %>
        <%= f.label(:type_teacher, "I am a Teacher") %><br>
        <%= f.radio_button(:type, "Student") %>
        <%= f.label(:type_student, "I am a Student") %><br>
        <%= f.radio_button(:type, "Parent") %>
        <%= f.label(:type_parent, "I am a Parent") %><br>
      </div>
      <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div>
        <%= f.submit "Submit" %> 
      </div>
    <% end %>
  <% end %>
  <p> Already have an account? <%= link_to "Login!", new_session_path %></p>
</div>